import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";


const exosans = Exo_2({
  subsets: ["latin"],
  variable: "--font-exo2-sans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={exosans.variable}>
      <body
        className="antialiased font-sans bg-linear-to-tr from-black to bg-background"
      >
        {children}
      </body>
    </html>
  );
}
